language: android

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+$/

jdk:
- oraclejdk8

env:
  global:
    - TERM=dumb

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

android:
  components:
  - tools
  - tools
  - platform-tools
  - build-tools-24.0.1
  - android-24
  - extra
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-24

script: ./gradlew build
